name: moneymonkey
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.4.2  # Downgrade to this version
  
  firebase_auth: ^5.3.0
  google_sign_in: ^6.1.5
     



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8


  #firebase
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  get: ^4.6.6
  firebase_core: ^3.4.1
  swipable_stack: ^0.2.1 
  flip_card: ^0.7.0
  swipeable_card_stack: ^0.0.5
  google_fonts: ^6.2.1
  confetti: ^0.8.0
  lottie: ^3.1.2
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  aligned_dialog: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/banknote.png
    - assets/images/bigbanana.png
    - assets/images/bigtreasure.png
    - assets/images/bluemonkey.png
    - assets/images/bottommonkey.png
    - assets/images/coin.png
    - assets/images/creditcard.png
    - assets/images/globemonkey.png
    - assets/images/hang.png
    - assets/images/image1.png
    - assets/images/img_group_4.svg
    - assets/images/img_group_5.svg
    - assets/images/img_group.svg
    - assets/images/img_monkeymoney_50.png
    - assets/images/img_monkeymoney_51.png
    - assets/images/img_monkeymoney_52.png
    - assets/images/img_screenshot_2024_08_26.png
    - assets/images/img_screenshot_2024_08_26_94x110.png
    - assets/images/img_screenshot_2024_08_26_1.png
    - assets/images/img_svgjsg1008.svg
    - assets/images/img_solar_book_bold.svg
    - assets/images/img_transparent_logo.png
    - assets/images/img_treasure_chest.png
    - assets/images/mobile.png
    - assets/images/monkeywithcap.png
    - assets/images/monkeywithnote.png
    - assets/images/rewardbanana.png
    - assets/images/rewardmonkey.png
    - assets/images/star.png
    - assets/images/treasure.png
    - assets/images/button.png
    - assets/images/monkey.png
    - assets/images/apple.png
    - assets/images/google.png
    - assets/images/banana.png
    - assets/images/bank.png
    - assets/images/navbar1.png
    - assets/images/navbar2.png
    - assets/images/navbar3.png
    - assets/images/navbar4.png
    - assets/images/banana_reward.json
    - assets/images/specsbanana.json
    - assets/images/swinging_monkey.json

  fonts:
    - family: Baloo 2
      fonts:
        - asset: assets/fonts/Baloo2Bold.ttf
          weight: 700
        - asset: assets/fonts/Baloo2Medium.ttf
          weight: 500
