// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYLfoa7GG2oQ83vu7ELAMQdfIHuO-3olY',
    appId: '1:921136508610:web:552393b9807ffaabbf555b',
    messagingSenderId: '921136508610',
    projectId: 'money-monkey-3bd68',
    authDomain: 'money-monkey-3bd68.firebaseapp.com',
    storageBucket: 'money-monkey-3bd68.appspot.com',
    measurementId: 'G-7FTCRTBYFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMEuO6TrDPBHgkOdTyL-40ZWRFwzywuZc',
    appId: '1:921136508610:android:50d2adc6531ea952bf555b',
    messagingSenderId: '921136508610',
    projectId: 'money-monkey-3bd68',
    storageBucket: 'money-monkey-3bd68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWwV4_HFqwLfDILD7iDzL49DFVl6ODS0Y',
    appId: '1:921136508610:ios:4282f4f06b3ddf44bf555b',
    messagingSenderId: '921136508610',
    projectId: 'money-monkey-3bd68',
    storageBucket: 'money-monkey-3bd68.appspot.com',
    iosBundleId: 'com.example.moneyMonkey',
  );

}