// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUs5eSHp6WDygKAdMZqo7wVG-04Cl9T5c',
    appId: '1:449424125948:web:c1f60b03cdb1f4ffeb0c79',
    messagingSenderId: '449424125948',
    projectId: 'money-monkey-468ee',
    authDomain: 'money-monkey-468ee.firebaseapp.com',
    storageBucket: 'money-monkey-468ee.appspot.com',
    measurementId: 'G-0HZ03S6KH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBvZtE28s72WsNqyQUYA73pvqhZoThclM',
    appId: '1:449424125948:android:a9af980533a1ecd8eb0c79',
    messagingSenderId: '449424125948',
    projectId: 'money-monkey-468ee',
    storageBucket: 'money-monkey-468ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhcepxhbjpQbI2EIss1VgQlkbdsDL_vAU',
    appId: '1:449424125948:ios:f3f2f119695885beeb0c79',
    messagingSenderId: '449424125948',
    projectId: 'money-monkey-468ee',
    storageBucket: 'money-monkey-468ee.appspot.com',
    iosBundleId: 'com.example.moneyMonkey',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhcepxhbjpQbI2EIss1VgQlkbdsDL_vAU',
    appId: '1:449424125948:ios:f3f2f119695885beeb0c79',
    messagingSenderId: '449424125948',
    projectId: 'money-monkey-468ee',
    storageBucket: 'money-monkey-468ee.appspot.com',
    iosBundleId: 'com.example.moneyMonkey',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUs5eSHp6WDygKAdMZqo7wVG-04Cl9T5c',
    appId: '1:449424125948:web:ec5b9df8fbbc38f3eb0c79',
    messagingSenderId: '449424125948',
    projectId: 'money-monkey-468ee',
    authDomain: 'money-monkey-468ee.firebaseapp.com',
    storageBucket: 'money-monkey-468ee.appspot.com',
    measurementId: 'G-LS62TB6X7W',
  );

}