// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYLfoa7GG2oQ83vu7ELAMQdfIHuO-3olY',
    appId: '1:921136508610:web:552393b9807ffaabbf555b',
    messagingSenderId: '921136508610',
    projectId: 'money-monkey-3bd68',
    authDomain: 'money-monkey-3bd68.firebaseapp.com',
    storageBucket: 'money-monkey-3bd68.appspot.com',
    measurementId: 'G-7FTCRTBYFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyFYwBCkYWF4fDMheevh66mJeO89sCeQQ',
    appId: '1:851718603804:android:da547fd5aa807baf458bd9',
    messagingSenderId: '851718603804',
    projectId: 'money-monkey-f4d73',
    databaseURL: 'https://money-monkey-f4d73-default-rtdb.firebaseio.com',
    storageBucket: 'money-monkey-f4d73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIMPvOB3MypmDch70fNsroXmWGh3aMMw0',
    appId: '1:851718603804:ios:93ee6341a4d42da0458bd9',
    messagingSenderId: '851718603804',
    projectId: 'money-monkey-f4d73',
    databaseURL: 'https://money-monkey-f4d73-default-rtdb.firebaseio.com',
    storageBucket: 'money-monkey-f4d73.appspot.com',
    iosBundleId: 'com.example.moneyMonkey',
  );
}
